DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS board;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   username TEXT NOT NULL UNIQUE,
   password TEXT NOT NULL,
   date_created TIMESTAMP DEFAULT now() NOT NULL
);

CREATE TABLE game_session (
    game_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_room TEXT UNIQUE,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    player_one_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    player_one_username TEXT REFERENCES users(username) ON DELETE CASCADE,
    player_one_score INTEGER DEFAULT '0',
    player_two_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
    player_two_username TEXT REFERENCES users(username) ON DELETE CASCADE,
    player_two_score INTEGER DEFAULT '0',
    current_player INTEGER REFERENCES users(id) ON DELETE CASCADE,
    board CHAR(9) DEFAULT '000000000',
    round INT DEFAULT '0'
);